# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

language:
  - python

python:
  - 3.6

# Environment variables
env:
  global:
    - GH_REPO_NAME: ruckus
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/slaclab/ruckus.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Generate and deploy documentation
jobs:
  include:
    - stage: document
      name: "Generate Documentation"
      script:
        - cd $TRAVIS_BUILD_DIR
        - chmod +x generateDocumentationAndDeploy.sh
        - ./generateDocumentationAndDeploy.sh
